/// A read-only projection of a `rol = 'cadete'` `profiles` row, just enough
/// to render a picker (design: "assign_cadete_sheet.dart") or the
/// dueño-only roster management screen ("manage_cadetes_screen.dart").
/// Deliberately not `AppSession` — a cadete's own session additionally
/// carries a `rol`, which is meaningless in a list the *dueño* is
/// browsing.
final class CadeteProfile {
  const CadeteProfile({required this.id, this.fullName, this.nro, this.active = true});

  final String id;
  final String? fullName;

  /// Dueño-assigned, manually-typed identifier (never autogenerated) — see
  /// migration 0021's doc comment. `null` until the dueño sets one.
  final int? nro;

  /// Whether this is a currently-active cadete account. Defaults to `true`
  /// since [listCadetes] (the picker's source) only ever returns active
  /// rows; only [listAllCadetes] (the management screen's source) can
  /// surface `false`.
  final bool active;

  /// Falls back to the id when `full_name` is null. `full_name` is always
  /// supplied through `createCadete`'s `nombre` field for accounts created
  /// in-app, but stays nullable to cover any account provisioned another
  /// way (e.g. directly in the Supabase Dashboard, still possible for an
  /// admin with project access).
  String get displayName => fullName?.trim().isNotEmpty == true ? fullName! : id;

  /// Display label used by the stats screen's cadete filter, e.g.
  /// "#03 - Carlos". Zero-padded to 2 digits (`nro` is meant to be small —
  /// a handful of couriers, not hundreds) so the list reads as a tidy
  /// column instead of "#3", "#12" misaligning visually. Falls back to
  /// [displayName] alone, no leading "#", when [nro] hasn't been set —
  /// there's nothing meaningful to pad.
  String get displayLabel {
    final number = nro;
    if (number == null) return displayName;
    return '#${number.toString().padLeft(2, '0')} - $displayName';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CadeteProfile &&
        other.id == id &&
        other.fullName == fullName &&
        other.nro == nro &&
        other.active == active;
  }

  @override
  int get hashCode => Object.hash(id, fullName, nro, active);
}

/// Port over listing, creating, and administering cadete accounts, so
/// dueño-facing UI never touches Supabase directly. Mirrors the
/// `AuthRepository`/`OrdersRepository` port pattern (design decision #1).
///
/// Every write method here lives on this same port rather than split
/// across several classes: they're all "how a dueño administers the
/// cadete roster", and the port is still small enough that splitting it
/// would just add extra files/providers/test doubles for no real
/// isolation benefit.
abstract interface class CadeteDirectory {
  /// Returns every ACTIVE `rol = 'cadete'` profile, ordered for display.
  /// This is the assignment-picker's source (`assign_cadete_sheet.dart`) —
  /// a dueño assigning a delivery should only ever see couriers currently
  /// on the roster. Relies on the `profiles_select_cadetes` RLS policy
  /// (migration 0003) to scope the read to an authenticated, active dueño.
  Future<List<CadeteProfile>> listCadetes();

  /// Returns EVERY `rol = 'cadete'` profile, active and inactive alike,
  /// ordered by `nro` then `full_name`. Backs the manage-cadetes screen
  /// (full roster CRUD) and the stats screen's cadete filter — both need
  /// to see a deactivated cadete too: the management screen so the dueño
  /// can reactivate them, the stats screen because past delivery numbers
  /// for a since-deactivated cadete are still real history worth pulling
  /// up, not something that should vanish from the filter the moment
  /// [setCadeteActive] flips them off.
  Future<List<CadeteProfile>> listAllCadetes();

  /// Creates a new cadete account (auth user + `profiles` row) via the
  /// `create-cadete` Edge Function, replacing the previous manual Supabase
  /// Dashboard provisioning process. [password] is handed to the cadete
  /// directly by the dueño — there is no invite-email flow. [nro] is
  /// optional (the dueño may not have a number ready at creation time —
  /// [updateCadete] can set it later).
  ///
  /// Returns the new user's id on success. Throws [CadeteDirectoryException]
  /// on any failure (validation, duplicate email, duplicate active `nro`,
  /// unauthorized caller, or an unexpected server error) with a
  /// user-facing message.
  Future<String> createCadete({
    required String email,
    required String password,
    required String nombre,
    int? nro,
  });

  /// Updates an existing cadete's `full_name`/`nro` (the "editar" half of
  /// CRUD). Writes directly to `profiles` — no Edge Function involved,
  /// since `profiles_update_cadetes_by_dueno` (migration 0021) already
  /// lets an active dueño write these columns for a `rol = 'cadete'` row.
  /// [nro] may be `null` to clear a previously-set number. Throws
  /// [CadeteDirectoryException] (e.g. a duplicate active `nro`, or the
  /// caller no longer being an active dueño so RLS silently drops the
  /// write).
  Future<void> updateCadete({required String id, required String nombre, int? nro});

  /// Flips a cadete's `active` flag — the CRUD's logical "D" (baja) and
  /// its reverse (reactivar). Never a physical delete: `orders.
  /// assigned_cadete_id` FK-references this row, so removing it outright
  /// would either fail the FK or, worse, silently orphan delivery
  /// history. An inactive cadete simply stops appearing in [listCadetes]
  /// (the assignment picker) and in `is_cadete()`-gated RLS checks,
  /// while [listAllCadetes] and past `orders` rows still see them fine.
  Future<void> setCadeteActive({required String id, required bool active});
}

/// Thrown by any [CadeteDirectory] write ([createCadete], [updateCadete],
/// [setCadeteActive]) on failure — a duplicate email, a duplicate active
/// `nro`, a validation error, an unauthorized caller (should not normally
/// happen since every entry point is already dueño-gated, but the
/// `create-cadete` Edge Function re-checks server-side regardless), or an
/// unexpected server error. [message] is safe to show directly to the
/// dueño.
final class CadeteDirectoryException implements Exception {
  const CadeteDirectoryException(this.message);

  final String message;

  @override
  String toString() => 'CadeteDirectoryException: $message';
}

/// Older name for [CadeteDirectoryException], kept as a `typedef` so every
/// existing `createCadete` call site/catch clause (predating [updateCadete]/
/// [setCadeteActive], back when only account creation could fail) keeps
/// compiling unchanged.
typedef CadeteCreationException = CadeteDirectoryException;
