-- ============================================================================
-- Migration: 0021_cadete_nro_and_admin_update.sql
-- Change: cadete-crud — Cadete roster administration (dueño-only)
--
-- Adds `profiles.nro`, a dueño-assigned integer identifying a cadete for
-- display/filtering purposes (e.g. "#03 - Carlos" in the stats screen's
-- cadete filter). Manually typed by the dueño — never autogenerated —
-- so it can match whatever numbering scheme they already use offline
-- (uniform IDs, delivery bags, etc). Nullable: a cadete created before
-- this migration, or one the dueño simply hasn't numbered yet, has no
-- `nro` and falls back to its name alone in the UI.
--
-- Also adds an UPDATE RLS policy letting an active dueño write to a
-- cadete's `profiles` row directly (full CRUD's "U" and logical-delete
-- "D" — baja is `active = false`, never a physical DELETE, since
-- `orders.assigned_cadete_id` FK-references this table and existing
-- delivery history must stay intact after a cadete is deactivated).
-- Until now only `profiles_update_own` (0001) existed, which is
-- self-only — a dueño had no way to edit another user's row at all.
--
-- Depends on: 0001_profiles.sql (`profiles` table, `is_active_dueno()`
-- added in 0004_fix_profiles_select_cadetes_recursion.sql).
--
-- HOW TO APPLY:
--   Local/CI with Supabase CLI:   supabase db push
--   Manually against a project:   paste this file's contents into the
--                                  Supabase Dashboard → SQL Editor and run it,
--                                  AFTER 0001-0020 are already applied.
--
-- ORDERING CONSTRAINT (same shape as 0013/0014/0015/0018/0020): apply
-- this migration BEFORE shipping an App build that reads/writes
-- `profiles.nro` or calls `.update()` on a cadete's `profiles` row —
-- PostgREST rejects a write referencing an unknown column, and the
-- update would otherwise be silently dropped by RLS (0 rows affected,
-- no error) rather than actually persisting.
-- ============================================================================

alter table public.profiles
  add column if not exists nro integer;

comment on column public.profiles.nro is
  'Dueño-assigned cadete number (e.g. 3, displayed as "#03"), manually typed in the manage-cadetes screen — never autogenerated. Null until the dueño sets one. Meaningless for rol=dueno rows.';

-- Partial unique index: two ACTIVE cadetes can never share a `nro` (the
-- dueño would have no way to tell them apart in the stats filter), but a
-- number frees up for reuse once its holder is deactivated — the dueño's
-- call, not enforced as a hard uniqueness constraint across all time.
create unique index if not exists profiles_cadete_nro_active_unique
  on public.profiles (nro)
  where rol = 'cadete' and active = true and nro is not null;

-- ----------------------------------------------------------------------------
-- Policy: profiles_update_cadetes_by_dueno
--
-- Mirrors `profiles_select_cadetes` (0003/0004)'s shape: an active dueño
-- may act on any `rol = 'cadete'` row, using `is_active_dueno()`
-- (SECURITY DEFINER) to avoid the same RLS self-recursion 0004 fixed for
-- the SELECT policy. `with check (rol = 'cadete')` blocks a dueño from
-- using this policy to flip a cadete's `rol` to something else — `id` is
-- the primary key and immutable regardless.
--
-- Scoped to `for update` only — a dueño still cannot INSERT (that stays
-- the `create-cadete` Edge Function's job, which needs the service-role
-- key to also create the matching `auth.users` row) or hard DELETE a
-- cadete's profile row through this policy.
-- ----------------------------------------------------------------------------
create policy profiles_update_cadetes_by_dueno
  on public.profiles
  for update
  using (
    rol = 'cadete'
    and public.is_active_dueno()
  )
  with check (
    rol = 'cadete'
  );

comment on policy profiles_update_cadetes_by_dueno on public.profiles is
  'Lets an active dueño update rol=cadete profile rows (full_name, nro, active) directly via the Supabase client — powers the manage-cadetes screen''s editar/baja/reactivar actions. Additive to profiles_update_own. with check pins rol=cadete so this policy cannot be used to change a row''s role.';

-- ============================================================================
-- Manual verification
--
-- 1. nro column + uniqueness:
--    a. As an active dueño, `update profiles set nro = 3 where id = '<cadete-A>'
--       and rol = 'cadete'`. Expect success, 1 row affected.
--    b. `update profiles set nro = 3 where id = '<cadete-B>' and rol = 'cadete'`
--       (a DIFFERENT active cadete). Expect a unique-violation error
--       (profiles_cadete_nro_active_unique).
--    c. Deactivate cadete A (`active = false`), then repeat (b) for cadete B
--       with nro = 3. Expect success this time — the partial index only
--       covers active rows.
--
-- 2. profiles_update_cadetes_by_dueno:
--    a. As an active dueño, `update profiles set full_name = 'Nuevo nombre'
--       where id = '<some cadete>' and rol = 'cadete'`. Expect success.
--    b. As an authenticated cadete (not dueño), attempt the same update
--       against ANOTHER cadete's row. Expect 0 rows affected (RLS filters
--       it out silently, no error — standard Postgres RLS UPDATE behavior).
--    c. As an active dueño, attempt `update profiles set rol = 'dueno' where
--       id = '<some cadete>'`. Expect a row-level security policy
--       violation (the `with check` rejects it).
-- ============================================================================
